"""Configuration for Moolo motor tests."""

LEFT_MOTOR_FORWARD_PIN = 5
LEFT_MOTOR_BACKWARD_PIN = 6
RIGHT_MOTOR_FORWARD_PIN = 13
RIGHT_MOTOR_BACKWARD_PIN = 19

A_MOTOR_REVERSED = True
B_MOTOR_REVERSED = False

DEFAULT_TEST_SPEED = 0.2
STEP_DURATION_SECONDS = 2.0
STOP_DURATION_SECONDS = 1.0
